import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { Building2, Mail, Phone, Search, Users } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

export default function TenantsIndex({ tenants, filters }) {
    const [search, setSearch] = useState(filters.search || '');
    const first = useRef(true);
    useEffect(() => {
        if (first.current) { first.current = false; return; }
        const timeout = setTimeout(() => router.get(route('tenants.index'), { search }, { preserveState: true, replace: true }), 350);
        return () => clearTimeout(timeout);
    }, [search]);

    return <AuthenticatedLayout header="Tenants"><Head title="Tenants" /><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="font-[Sora] text-2xl font-bold text-gray-900">Tenants</h1><p className="mt-1 text-sm text-gray-500">Manage the people and businesses occupying your units.</p></div><div className="relative w-full sm:w-72"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search tenants..." className="w-full rounded-xl border border-gray-200 bg-white py-2.5 pl-9 pr-3 text-sm focus:border-[#0E3B2E] focus:ring-2 focus:ring-[#0E3B2E]/15" /></div></div><div className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm">{tenants.data.length ? <div className="divide-y divide-gray-100">{tenants.data.map(tenant => <div key={tenant.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#0E3B2E]/5"><Users size={20} className="text-[#0E3B2E]" /></div><div><div className="flex items-center gap-2"><h3 className="font-semibold text-gray-900">{tenant.name}</h3><span className="rounded-full bg-gray-100 px-2 py-0.5 text-[10px] font-semibold uppercase text-gray-500">{tenant.type}</span></div><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-500">{tenant.email && <span className="inline-flex items-center gap-1"><Mail size={12} />{tenant.email}</span>}{tenant.phone && <span className="inline-flex items-center gap-1"><Phone size={12} />{tenant.phone}</span>}</div></div></div><div className="flex items-center gap-4 text-sm text-gray-500"><span className="inline-flex items-center gap-1.5"><Building2 size={15} />{tenant.active_tenancies_count} active unit{tenant.active_tenancies_count === 1 ? '' : 's'}</span>{tenant.active_tenancies?.[0]?.unit?.property && <span className="hidden text-xs text-gray-400 md:inline">{tenant.active_tenancies[0].unit.property.name}</span>}</div></div>)}</div> : <div className="p-14 text-center"><Users size={44} className="mx-auto text-gray-300" /><h3 className="mt-4 font-semibold text-gray-900">No tenants found</h3><p className="mt-1 text-sm text-gray-500">{search ? 'Try a different search.' : 'Tenants will appear here when assigned to a unit.'}</p></div>}{tenants.links?.length > 3 && <div className="flex flex-wrap gap-2 border-t border-gray-100 p-4">{tenants.links.map((link, i) => <Link key={i} href={link.url || '#'} className={`rounded-lg px-3 py-1.5 text-sm ${link.active ? 'bg-[#0E3B2E] text-white' : 'bg-gray-50 text-gray-600'} ${!link.url ? 'pointer-events-none opacity-40' : ''}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div>}</div></AuthenticatedLayout>;
}
